### ISSUE TITLE
run time error:ogrplugin

### ISSUE THREAD

**Issue by ajransaputra** [samthomson/picmap#3]
i get error this sam : 
Traceback (most recent call last):
  File "./picmap/src/picmap.py", line 131, in <module>
    layer.datasource = mapnik.Ogr(file="/picmap/out/kml_geo.kml", layer_by_index=0)
  File "/usr/local/lib/python2.7/site-packages/mapnik/__init__.py", line 589, in Ogr
    return CreateDatasource(keywords)
RuntimeError: OGR Plugin: only 0 layer(s) exist, cannot find layer by index '0'

**Comment by samthomson** [comment]
Can you confirm the files in your seed folder are geotagged?

**Comment by ajransaputra** [comment]
That it my problem, seed folder empty,i dont know what kind of files in seed folder. Can you add example file in seed folder? Thanks before sam

**Comment by samthomson** [comment]
You have to edit the docker-compose file:
https://github.com/samthomson/picmap/blob/master/docker-compose.yml#L8 and add your own seed folder path. So replacing `/home/sam/Dropbox/folder-to-map-into-picmap` with a path to a folder on your machine. That folder should contain jpegs which are geo-tagged (ie. contain latitude/longitude exif data).
Do you have geotagged images?
Re-open **this** issue if your problem persists :upside_down_face: 

The specific error the program has printed is a result of their being no geo-data to render.
