### ISSUE TITLE
geotagged images

### ISSUE THREAD

**Issue by ajransaputra** [samthomson/picmap#4]
thanks for explanation https://github.com/samthomson/picmap/blob/master/docker-compose.yml#L8 im understand. can you share geotagged images? i dont have geotagged images before

**Comment by samthomson** [comment]
If you don't have geotagged pictures what are you looking to use the software for? It's for rendering geotagged pictures.
You can geotag existing images you have with free geotagging software like https://www.geosetter.de/en/main-en/ and then use this project (picmap) to render them on a map.
